# Use an official Python runtime as a parent image
FROM python:3.11-slim-buster

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /convert

# Install dependencies
COPY ./requirements.txt .
RUN pip install --upgrade pip
RUN pip install --upgrade -r requirements.txt

# Copy project
COPY /convert .
